LLM_info:
  LLM_repo:
  - meta-llama/Llama-2-7b-chat-hf
  preset_prompt: true
  save_directory: Inference_result
  vllm_configs:
    dtype: float16
    gpu_memory_utilization: 0.9
    sampling_params:
      max_tokens: 256
      temperature: 0.1
      top_p: 0.1
    tensor_parallel_size: 1
mode: RAG
prompt: {}
retriever_info:
  retriever_batch_size: 1024
  retriever_repo:
  - BAAI/bge-small-en-v1.5
  save_directory: Retrieval_result
  top_k: 5
  use_cuda: true
