"""
Standalone script to generate mock data for MIRAGE Dashboard frontend development.
Run this script manually when you need to test the UI without running real LLMs.

Usage:
    python seed_data.py
"""

import os
import json
import uuid
import random
import argparse
from datetime import datetime, timezone
import asyncio
from backend.config import get_settings
from backend.database import get_db_connection, init_db, create_experiment

settings = get_settings()

def generate_mock_inference_data(llm_id: str, retriever_id: str = None, mode: str = "base"):
    data = []
    for i in range(50):
        query_id = str(uuid.uuid4())
        data.append({
            "source": random.choice(["popqa", "triviaqa"]),
            "query_id": query_id,
            "query": f"Mock Question {i}?",
            "doc_name": f"Mock Document {i}",
            "answer": [f"Mock Answer {i}", "Alternate Answer"],
            "doc_url": f"https://example.com/doc/{i}",
            "num_doc_labels": 1,
            "model_predictions": [f"This is a mock prediction for question {i} generated by {llm_id}"],
            "EM_label": random.choice([0.0, 1.0]),
            "EM_strict": random.choice([0.0, 1.0]),
        })
    return data

def generate_mock_retrieval_data():
    data = []
    for i in range(50):
        query_id = str(uuid.uuid4())
        top_chunks = []
        for k in range(5):
            top_chunks.append({
                "mapped_id": query_id if random.random() > 0.5 else str(uuid.uuid4()),
                "doc_name": f"Chunk Doc {k}",
                "doc_chunk": f"Mock text content for chunk {k}",
                "support": 1 if random.random() > 0.5 else 0
            })
            
        data.append({
            "query_id": query_id,
            "top_chunks": top_chunks,
            "scores": sorted([random.random() for _ in range(5)], reverse=True)
        })
    return data


def create_mock_files():
    settings.ensure_dirs()
    
    llms = ["gpt-3.5-turbo", "gpt-4o", "meta-llama/Llama-2-7b-chat-hf"]
    retrievers = ["BAAI/bge-small-en-v1.5", "BAAI/bge-base-en-v1.5"]
    
    # 1. Retrieval_result
    print("Generating mock retrieval results...")
    for ret in retrievers:
        ret_id = ret.split("/")[-1]
        ret_data = generate_mock_retrieval_data()
        with open(settings.abs_retrieval_dir / f"{ret_id}_top5.json", "w", encoding="utf-8") as f:
            json.dump(ret_data, f, indent=4)
            
    # 2. Inference_result
    print("Generating mock inference results...")
    for llm in llms:
        llm_id = llm.split("/")[-1]
        
        # Base
        with open(settings.abs_inference_dir / f"{llm_id}_base.json", "w", encoding="utf-8") as f:
            json.dump(generate_mock_inference_data(llm_id, mode="base"), f, indent=4)
        with open(settings.abs_inference_dir / f"{llm_id}_base_eval.json", "w", encoding="utf-8") as f:
            json.dump(generate_mock_inference_data(llm_id, mode="base"), f, indent=4)
            
        # Oracle
        with open(settings.abs_inference_dir / f"{llm_id}_oracle.json", "w", encoding="utf-8") as f:
            json.dump(generate_mock_inference_data(llm_id, mode="oracle"), f, indent=4)
        with open(settings.abs_inference_dir / f"{llm_id}_oracle_eval.json", "w", encoding="utf-8") as f:
            json.dump(generate_mock_inference_data(llm_id, mode="oracle"), f, indent=4)
            
        # RAG (with each retriever)
        for ret in retrievers:
            ret_id = ret.split("/")[-1]
            with open(settings.abs_inference_dir / f"{llm_id}_{ret_id}_top5.json", "w", encoding="utf-8") as f:
                json.dump(generate_mock_inference_data(llm_id, ret_id, mode="top5"), f, indent=4)
            with open(settings.abs_inference_dir / f"{llm_id}_{ret_id}_top5_eval.json", "w", encoding="utf-8") as f:
                json.dump(generate_mock_inference_data(llm_id, ret_id, mode="top5"), f, indent=4)

    # 3. Evaluation_result
    print("Generating mock evaluation JSONL files...")
    llm_eval_lines = []
    metrics_lines = []
    ret_eval_lines = []

    for llm in llms:
        llm_id = llm.split("/")[-1]
        
        # Base/Oracle LLM records
        llm_eval_lines.append(json.dumps({
            "LLM_name": llm_id, "Retriever_name": None, "Given_shot": "base",
            "F1_score": random.random(), "EM_loose": random.random(), "EM_strict": random.random()
        }))
        llm_eval_lines.append(json.dumps({
            "LLM_name": llm_id, "Retriever_name": None, "Given_shot": "oracle",
            "F1_score": random.random(), "EM_loose": random.random(), "EM_strict": random.random()
        }))
        
        for ret in retrievers:
            ret_id = ret.split("/")[-1]
            
            # RAG LLM record
            llm_eval_lines.append(json.dumps({
                "LLM_name": llm_id, "Retriever_name": ret_id, "Given_shot": "top5",
                "F1_score": random.random(), "EM_loose": random.random(), "EM_strict": random.random()
            }))
            
            # Metrics record
            metrics_lines.append(json.dumps({
                "LLM_name": llm_id, "Retriever_name": ret_id, "Given_shot": "top5",
                "Scores": {
                    "noise_vulnerability": random.random() * 0.3,
                    "context_acceptibility": random.random() * 0.5,
                    "context_insensitivity": random.random() * 0.2,
                    "context_misinterpretation": random.random() * 0.2,
                },
                "Counts": {
                    "label_count": {"0_0_0": 10, "0_0_1": 5, "0_1_0": 2, "0_1_1": 15, "1_0_0": 1, "1_0_1": 3, "1_1_0": 4, "1_1_1": 10},
                    "metrics": {"nv": 5, "ca": 15, "ci": 1, "cm": 4},
                    "total": 50
                }
            }))
            
    for ret in retrievers:
        ret_id = ret.split("/")[-1]
        avg_results = {}
        for k in [1, 3, 5]:
             avg_results[str(k)] = {
                 "F1": f"{random.random():.5f}", "NDCG": f"{random.random():.5f}",
                 "precision": f"{random.random():.5f}", "recall": f"{random.random():.5f}"
             }
        ret_eval_lines.append(json.dumps({
            "Retriever_name": ret_id, "Average_results": avg_results
        }))

    with open(settings.abs_evaluation_dir / "LLM_result.jsonl", "w", encoding="utf-8") as f:
        f.write("\n".join(llm_eval_lines) + "\n")
        
    with open(settings.abs_evaluation_dir / "Metrics.jsonl", "w", encoding="utf-8") as f:
        f.write("\n".join(metrics_lines) + "\n")
        
    with open(settings.abs_evaluation_dir / "RET_result.jsonl", "w", encoding="utf-8") as f:
        f.write("\n".join(ret_eval_lines) + "\n")
        
    # Generate mock aggregates for the DB
    return llms, retrievers

async def seed_database(llms, retrievers):
    print("Seeding SQLite database...")
    await init_db()
    db = await get_db_connection()
    
    # Create one completed RAG experiment
    exp_id = str(uuid.uuid4())
    config = {
        "mode": "RAG",
        "LLM_info": {"LLM_repo": [llms[0]], "vllm_configs": {"sampling_params": {"temperature": 0.1, "top_p": 0.1, "max_tokens": 256}}},
        "retriever_info": {"retriever_repo": [retrievers[0]], "top_k": 5}
    }
    await create_experiment(db, {
        "id": exp_id,
        "name": "Mock RAG Run",
        "mode": "RAG",
        "config": config,
    })
    
    # Compute mock aggregates
    aggregates = {
        "summary": {
            "avg_em_loose": 0.55, "avg_em_strict": 0.42, "avg_f1": 0.61,
            "avg_nv": 0.1, "avg_ca": 0.4, "avg_ci": 0.1, "avg_cm": 0.05
        },
        "per_llm": [{"llm": llms[0], "em_loose": 0.55}],
        "per_retriever": [{"retriever": retrievers[0], "recall_at_5": 0.8}],
        "per_pair": [{"llm": llms[0], "retriever": retrievers[0], "f1": 0.61}],
        "chart_data": {
            "context_metrics": [
                {"name": "NV", "value": 0.1},
                {"name": "CA", "value": 0.4},
                {"name": "CI", "value": 0.1},
                {"name": "CM", "value": 0.05}
            ]
        }
    }
    
    # Write to aggregates json
    with open(settings.abs_evaluation_dir / f"{exp_id}_aggregates.json", "w") as f:
        json.dump(aggregates, f, indent=4)
        
    await db.execute(
        """UPDATE experiments 
           SET status = 'completed', started_at = ?, completed_at = ?, aggregates = ? 
           WHERE id = ?""",
        (datetime.now(timezone.utc).isoformat(), datetime.now(timezone.utc).isoformat(), json.dumps(aggregates), exp_id)
    )
    
    await db.execute("INSERT INTO activity_log (experiment_id, event, message) VALUES (?, 'completed', 'Mock run finished')", (exp_id,))
    await db.commit()
    await db.close()
    
    print(f"Mock experiment ID: {exp_id}")
    print("Seed complete! You can now run the backend and see data in the UI.")

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--clear", action="store_true", help="Clear existing files before seeding")
    args = parser.parse_args()
    
    if args.clear:
        pass # Optional: implement clearing
        
    llms, retrievers = create_mock_files()
    asyncio.run(seed_database(llms, retrievers))

if __name__ == "__main__":
    main()
